name: build-test

on:
  pull_request:
  push:
    branches:
      - 'master'
      - 'stable/**'

defaults:
  run:
    shell: bash

jobs:
  build-x86-docker:
    name: Build the x86 ubuntu 22.04 docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Build docker image
        run: |
          docker build --no-cache -t frr-x86-ubuntu22 -f docker/ubuntu-ci/Dockerfile .
          docker save --output /tmp/frr-x86-ubuntu22.tar frr-x86-ubuntu22
      - name: Upload docker image artifact
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu-x86-image
          path: /tmp/frr-x86-ubuntu22.tar
      - name: Clear any previous results
        # So if all jobs are re-run then all tests will be re-run
        run: |
          rm -rf test-results-x86*
          mkdir -p test-results-x86
          touch test-results-x86/cleared-results.txt
      - name: Save cleared previous results
        uses: actions/upload-artifact@v4
        with:
          name: test-results-x86
          path: test-results-x86
          overwrite: true
      - name: Cleanup
        if: ${{ always() }}
        run: rm -rf test-results-x86* /tmp/frr-x86-ubuntu22.tar

  build-arm-docker:
    name: Build the ARM ubuntu 22.04 docker image
    runs-on: ubuntu-22.04-arm
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Build docker image
        run: |
          docker build --no-cache -t frr-arm-ubuntu22 -f docker/ubuntu-ci/Dockerfile .
          docker save --output /tmp/frr-arm-ubuntu22.tar frr-arm-ubuntu22
      - name: Upload docker image artifact
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu-arm-image
          path: /tmp/frr-arm-ubuntu22.tar
      - name: Clear any previous results
        # So if all jobs are re-run then all tests will be re-run
        run: |
          rm -rf test-results-arm*
          mkdir -p test-results-arm
          touch test-results-arm/cleared-results.txt
      - name: Save cleared previous results
        uses: actions/upload-artifact@v4
        with:
          name: test-results-arm
          path: test-results-arm
          overwrite: true
      - name: Cleanup
        if: ${{ always() }}
        run: rm -rf test-results-arm* /tmp/frr-arm-ubuntu22.tar
